### Input configuration
#
# Example configuration:
#
#   input "2:14:SynPS/2_Synaptics_TouchPad" {
#       dwt enabled
#       tap enabled
#       natural_scroll enabled
#       middle_emulation enabled
#   }
#
# You can get the names of your inputs by running: swaymsg -t get_inputs
# Read `man 5 sway-input` for more information about this section.

input type:touchpad {
    # Enable natural scroll
    natural_scroll enabled
    # Disable-while-typing
    dwt enabled
    # Disable-while-trackpointing
    dwtp enabled
    # Enable tap
    tap enabled
    # 2-finger tap for right click
    tap_button_map lrm
}

input type:keyboard {
    # Enable numlock by default
    xkb_numlock enabled
}
