# Gaps and Borders
gaps inner 5
gaps outer 5
default_border pixel 2
default_floating_border normal 2
hide_edge_borders smart

# Blur, rounded corners, and shadows
blur enable
blur_passes 2
blur_radius 3

corner_radius 10

shadows enable
shadow_offset 5 5
shadow_color #111111
shadow_inactive_color #0000004F

default_dim_inactive 0.1
for_window [app_id=".*"] opacity 1

# target                 title     bg    text   indicator  border
client.focused           $lavender $base $text  $rosewater $lavender
client.focused_inactive  $overlay0 $base $text  $rosewater $clear
client.unfocused         $overlay0 $base $text  $rosewater $clear
client.urgent            $peach    $base $peach $overlay0  $peach
client.placeholder       $overlay0 $base $text  $overlay0  $overlay0
client.background        $base

# Disable focus changes on hover
focus_follows_mouse no