source = $HOME/.config/hypr/mocha.conf

$accent = $overlay2Alpha
$accentAlpha = $baseAlpha
$font = Roboto

# General
general {
  hide_cursor = true
}

# Background
background {
  monitor =
  path = /usr/share/wallpapers/Mountain/contents/images_dark/5120x2880.png
  blur_passes = 1
  color = $base
}

# Layout
label {
  monitor =
  text = $LAYOUT
  color = $text
  font_size = 10
  font_family = $font
  position = 0, 0
  halign = right
  valign = bottom
}

# Lock icon
label {
    monitor =
    text = <span> </span>
    color = $textAlpha
    font_size = 24
    font_family = $font
    position = 2, -110
    halign = center
    valign = top
}

# Time
label {
  monitor =
  text = $TIME
  color = $textAlpha
  font_size = 60
  font_family = $font
  position = 0, 200
  halign = center
  valign = center
}

# Date
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $textAlpha
  font_size = 25
  font_family = $font
  position = 0, 130
  halign = center
  valign = center
}

# User avatar
image {
  monitor =
  path = $HOME/Pictures/avatar.png
  size = 100
  border_color = $accent
  position = 0, 0
  halign = center
  valign = center
}

# Username
label {
    monitor =
    text = Logged in as $USER
    color = $textAlpha
    font_size = 15
    font_family = $font Italic
    position = 0, -80
    halign = center
    valign = center
}

# Input field
input-field {
  monitor =
  size = 300, 60
  outline_thickness = 1
  dots_size = 0.1
  dots_spacing = 1
  dots_center = true
  outer_color = $accent
  inner_color = $surface0
  font_size = 8
  font_family = $font
  font_color = $text
  fade_on_empty = false
  placeholder_text = <span foreground="##$textAlpha">Enter password</span>
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, -150
  halign = center
  valign = center
}
